bootstrap.servers=localhost:29092
ws.port=8081

acks=1

session.timeout.ms=45000
auto.offset.reset=latest
enable.auto.commit=true
retries=10
retry.backoff.ms=200
delivery.timeout.ms=60000
reconnect.backoff.max.ms=10000

player.event.topic=player-event
player.updates.topic=player-update
location.updates.topic=location-update
game.updates.topic=game-update
game.round.time = 125
